### ISSUE TITLE
Node SDK 2.0 计划

### ISSUE THREAD

**Issue by jysperm** [leancloud/leanengine-node-sdk#100]
主要是为了在更新 JavaScript SDK 2.0 的时候顺便做一些不兼容的修改，尽量能够在一个月内发布：

- [x] 更新 JavaScript SDK 2.0（不兼容，小程序相关支持）
- [x] 移除 AV.Cloud.httpRequest（不兼容）
- [x] 云函数 Promise 支持、移除 domain、onError（少量不兼容） https://github.com/leancloud/leanengine-node-sdk/issues/90 https://github.com/leancloud/leanengine-node-sdk/issues/67 https://github.com/leancloud/leanengine-node-sdk/issues/96
- [x] 向 res.saveCurrentUser 传入没有 sessionToken 的用户时需要向用户发出警告（细微不兼容） https://github.com/leancloud/leanengine-node-sdk/issues/80
- [x] 不正确的云函数名称、重复的云函数抛异常（细微不兼容）

还有一些不太可能引起不兼容的修改，可以做也可以往后放一放：

- [ ] beforeUpdate 支持用户指定允许更新的字段（细微不兼容） https://github.com/leancloud/leanengine-node-sdk/issues/59
- [x] 提供一个根据 Header 中的  sessionToken 获取用户的中间件，主要是为了对微信小程序提供支持 https://forum.leancloud.cn/t/leancloud/11434
- [ ] koa2 支持（可能有细微不兼容）
- [x] 新的 Hook Key 重构（可能有细微不兼容） https://github.com/leancloud/uluru-platform/issues/2384
- [x] TypeScript 定义文件 https://github.com/leancloud/leanengine-node-sdk/issues/98
- [x] 包装 _messageReceived 等实时通讯 hook

**Comment by chenshuhong** [comment]
还没升级到2.0吗？

**Comment by jysperm** [comment]
还在开发，估计半个月到一个月内可以发布一个版本

**Comment by BinaryHB** [comment]
Mark。用户需求：https://forum.leancloud.cn/t/node-js-containin/13319

**Comment by jysperm** [comment]
准备先发一个 alpha 版本供对 2.0 有强烈需求的用户使用，在 2.0 正式发布前还会有其他不兼容的改动

**Comment by jysperm** [comment]
可以用 `npm install leanengine@next` 来安装

**Comment by jysperm** [comment]
https://github.com/leancloud/leanengine-node-sdk/releases
发布了 Node SDK 2.0 和 3.0 的测试版。

**Comment by jysperm** [comment]
2.0 已正式发布
